### ISSUE TITLE
Not able to send SNMP V3 traps with SHA256 Authentication and AES192 Encryption

### ISSUE THREAD

**Issue by Gaurav-Singh7** [lextudio/sharpsnmplib-samples#15]
Hi @lextm ,

I am able to send V3 traps using MD5 and DES. But when I try to send V3 traps using SHA256 and AES192, I am getting an error at the  Manager saying "Failed to decrypt encrypted PDU using privacy password ". Can you help with this?

**Comment by lextm** [comment]
More details are needed. It is likely that you didn't enable those algorithms on manager side, which is a very common cause.
