### ISSUE TITLE
Lextm.SharpSnmpLib.BouncyCastle is no more published to NuGet.org

### ISSUE THREAD

**Issue by lextm** [lextudio/sharpsnmplib-samples#4]
After moving the sample code here in this repo and the support policy changes, this NuGet package is discontinued.

Users can compile their own from the source code so as to enable .NET Core usage.

**Comment by deapsquatter** [comment]
I'm a little confused as to to the recommended approach to handling SNMP V3 Encryption now for .NET Core. Should Lextm.SharpSnmpLib.BouncyCastle .cs files be used (as in the samples) or is it ok just to use the the PrivacyProviders in .NET Core?

**Comment by lextm** [comment]
https://docs.sharpsnmp.com/tutorials/aes.html#providers-on-bouncy-castle

Sample code is provided.
